const questions = [
    {
        id:1,
        question: "1. Do you have a Sore Throat?",
        option1:"Yes",
        option2:"No",
    },
    {id:2,
        question: "2. Do you have a headache?",
        option1:"Yes",
        option2:"No",
    },
    {id:3,
        question: "3. Are you feeling tired?",
        option1:"Yes",
        option2:"No",
    },
    {id:4,
        question: "4. Do you feel pain or pressure in the chest?",
       option1:"Yes",
        option2:"No",
    },
    {id:5,
        question: "5. Do you have a High Fever?",
        option1:"Yes",
        option2:"No",
    },
    {id:6,
        question: "6. Do you have running nose?",
        option1:"Yes",
        option2:"No",
    },
    {id:7,
        question: "7. Are you having difficulty while breathing?",
        option1:"Yes",
        option2:"No",
    },
    {id:8,
        question: "8. Are you a frequent traveller? Did you travel to any city within the last 15 days?",
        option1:"Yes",
        option2:"No",
    },
    {id:9,
        question: "9. Are you suffering from health problems like cold or cough?",
        option1:"Yes",
        option2:"No",
    },
    {id:10,
        question: "10. Are you able to smell everything perfectly? ",
        option1:"Yes",
        option2:"No",
    }

];

export default questions;